#' Create the \pkg{TMB} wrapper file for parameter estimation with user-defined models.
#'
#' @param model Name of model.
#' @param header Name of model header file including extension.  If missing defaults to `{model}.hpp`.  (See 'Details').
#' @param class Name of class definition, with enclosing namespace if it exists.  If missing defaults to `{model}`.  (See 'Details').
#' @param ctor Name of external class constructor, with enclosing namespace if it exists.  If missing defaults to `make_{model}`.  (See 'Details').
#' @param standalone If `TRUE` creates a standalone `cpp` file to pass to [TMB::compile()].  Otherwise, creates an `hpp` header file to be placed in a package created with \pkg{TMBtools}. (See 'Details').
#'
#' @return Vector of strings each containing one line of the \pkg{TMB} wrapper file.
#' @export
make_psd_model <- function(model, header, class, ctor, standalone = TRUE) {
  # check missing inputs
  ## if(missing(name)) name <- "MyModel"
  if(missing(header)) header <- paste0(model, ".hpp")
  if(missing(class)) class <- model
  if(missing(ctor)) ctor <- paste0("make_", model)
  method <- "realPSD::FitMethods"
  ## if(!missing(method)) {
  ##   if(missing(include)) include <- file.path(".", paste0(method, ".hpp"))
  ## }
  ## if(dir.exists(path)) error(paste0(path, "already exists!"))
  # read template header file
  template <- readLines(system.file("include", "realPSD", "Model_Template.hpp",
                                    package = "realPSD"))
  # set up whisker render
  settings <- list(
    Model = model, # "fou"
    Header = header, # "fou.hpp"
    Class = class, # fou::UFun
    Ctor = ctor, # "fou::make_Ufun"
    ## Include = include, # "realPSD/FitMethods.hpp"
    GenericMethods = method, # "realPSD::FitMethods"
    # if standalone == TRUE, show the part of the code for on-the-fly compilation
    Standalone = standalone
  )
  whisker::whisker.render(template, settings)
  ## # output
  ## if(standalone) { # create a .cpp file to pass to TMB::compile()
  ##   if(is.null(path)) {
  ##     return(print(model_scr))
  ##   } else {
  ##     if(missing(path)) path <- paste0(model, "_Generics.cpp")
  ##     output_dir <- file.path(".", path)
  ##     writeLines(model_scr, path)
  ##     return(paste0("C++ source file has been created under ", output_dir))
  ##   }
  ## } else { # create a .hpp file within a package generated by TMBtools
  ##   if(is.null(path)) {
  ##     return(print(model_scr))
  ##   } else {
  ##     if(missing(path)) path <- paste0(model, "_Generics.hpp")
  ##     output_dir <- file.path(".", path)
  ##     writeLines(model_scr, path)
  ##     return(paste0("C++ header file has been created under ", output_dir))
  ##   }
  ## }
}

#` @param include Name of additional include directive (path of the additional header file), usually package specific, e.g. #include"realPSD/FitMethods.hpp" .
#` @param method Name of generic method class with enclosing namespace if it exists. To use realPSD, method = "realPSD::FitMethods" is mandatory.
#` @param path Name of output file.  If missing defaults to `{model}_Generics.{cpp/hpp}` depending on the value of `standalone`.  If `NULL` doesn't create file but prints contents to console.  Generates an error if `path` file already exists.
