---
title: "**realPSD**: Simulation Tutorial"
author: "Feiyu Zhu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simulation tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
require(fftw)
require(realPSD)
```

## simulation tutorial

We first simulate the data from SHO model by using the following code

```{r sim}
save_name <- 'Jul_2'  # save name
simNum <- 10          # number of simulated datasets 
seed <- 123           # random seed
model_type <- 'SHOW'  # SHOW or SHOWF
bin_size <- 100       # size of bins for fitting
T  <- 5               # Total time
SF <- 1e7             # Sampling frequency
f0 <- 33553           # Resonance frequency, Hz
Q  <- 500             # Quality factor
alpha <- 0.55         # 1/f decay exponent
k  <- 0.172           # Cantilever stiffness, N/m
Kb <- 1.381e-23 # Boltzmann's constant
T <- 298        # Temperature, Kelvin
CONST <- 1e30   # unit conversion constant
As_s <- 4*Kb*T/(k_s*Q_s*f0_s*2*pi) * CONST  # SHO
Aw_s <- 19000                               # white noise
Af_s <- 0                                   # 1/f noise
f_lowerBound <- f0_s - f0_s/sqrt(2)
f_upperBound <- f0_s + f0_s/sqrt(2)
# Transfer Functions
f <- seq(from = 1/T_s, to = SF_s, length.out = SF_s*T_s) # freq space.
# [C, abs_C, theta_C, funcSHO] = Get_SHO(f, f0_s, Q_s, k_s)
sho <- getSHO(f, f0_s, Q_s, k_s)
C <- sho$C
abs_C <- sho$abs_C
theta_C <- sho$theta_C
g <- k_s/2/pi/f0_s/Q_s

xAPSD <- f # change naming convention
yAPSD <- (4*Kb*T*g) * abs_C^2 * CONST # drive by thermal physics
yAPSD <- yAPSD + Aw_s
yAPSD <- yAPSD + Af_s * 1/xAPSD^alpha_s

# -----------------------------
# Simulation
CORRUPT <- 1
res <- list("Baseline" = list(), "Noised" = list(), "Denoised" = list())
id <- paste0('Q', Q_s, "_SFM", SF_s/1e6, "_C", CORRUPT, "_B", binfit_size)

# Row: Sim #
# Col: 1: Clean, 2: Noised, 3: Denoised
# Depth: Layer 1: NLSQ, Layer 2: LOGP, Layer 3: MLE
As_vec <- array(NA, dim = c(3,3,simNum))
Aw_vec <- array(NA, dim = c(3,3,simNum))
f0_vec <- array(NA, dim = c(3,3,simNum))
Q_vec <- array(NA, dim = c(3,3,simNum))
Af_vec <- array(NA, dim = c(3,3,simNum))
alpha_vec <- array(NA, dim = c(3,3,simNum))
exitflag_vec <- array(NA, dim = c(3,3,simNum))

# simulation for loop
system.time(
for(ii in 1:simNum) {
  # print the iteration number
  simstr <- paste0("Sim_", ii)
  print(simstr)
  # generate (1) clean data (2) corrupted data (3) denoised data

}
)

```

